import type { StyleDescription } from "@/types/caption"

export type StyleCategory =
  | "photography"
  | "rendered"
  | "illustrated"
  | "classical"
  | "aesthetic"
  | "horror"

export interface StylePreset {
  id: string
  label: string
  category: StyleCategory
  mode: "photo" | "illustration"
  fields: Partial<Omit<StyleDescription, "mode" | "color_palette">>
}

export const STYLE_CATEGORIES: { key: StyleCategory; label: string }[] = [
  { key: "photography", label: "Photography" },
  { key: "rendered",    label: "Rendered / 3D" },
  { key: "illustrated", label: "Illustrated" },
  { key: "classical",   label: "Classical Painting" },
  { key: "aesthetic",   label: "Wonderful & Aesthetic" },
  { key: "horror",      label: "Weird & Horror" },
]

export const STYLE_PRESETS: StylePreset[] = [
  // ── Photography ────────────────────────────────────────────────────────────
  {
    id: "cinematic",
    label: "Cinematic",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "cinematic, widescreen, dramatic, filmic",
      lighting:   "golden hour, volumetric light, lens flare",
      photo:      "anamorphic lens, shallow depth of field, f/1.8",
      medium:     "film photography",
    },
  },
  {
    id: "product",
    label: "Product",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "clean, commercial, minimalist, professional",
      lighting:   "studio lighting, softbox, white background",
      photo:      "macro lens, sharp focus, f/8",
      medium:     "product photography",
    },
  },
  {
    id: "editorial",
    label: "Editorial",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "editorial, luxury, sophisticated, magazine-quality",
      lighting:   "professional studio lighting, dramatic shadows",
      photo:      "portrait lens, 85mm",
      medium:     "fashion photography",
    },
  },
  {
    id: "documentary",
    label: "Documentary",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "raw, authentic, candid, journalistic",
      lighting:   "natural available light, harsh midday or overcast",
      photo:      "35mm, grain, reportage style",
      medium:     "documentary photography",
    },
  },
  {
    id: "street",
    label: "Street",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "gritty, urban, spontaneous, decisive-moment energy",
      lighting:   "harsh sunlight and deep shadow, neon at night",
      photo:      "28mm, zone focus, slight motion blur",
      medium:     "street photography",
    },
  },
  {
    id: "film-noir",
    label: "Film Noir",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "moody, mysterious, high-contrast monochrome, 1940s crime drama",
      lighting:   "single hard key light, venetian-blind shadows, cigarette smoke haze",
      photo:      "50mm, deep blacks, silver gelatin look",
      medium:     "black and white film photography",
    },
  },
  {
    id: "golden-portrait",
    label: "Golden Hour",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "warm, intimate, sun-kissed, glowing",
      lighting:   "low golden-hour sun, rim light, soft flare, long shadows",
      photo:      "85mm portrait lens, f/1.4, creamy bokeh",
      medium:     "portrait photography",
    },
  },
  {
    id: "macro",
    label: "Macro",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "intricate, otherworldly detail, abstract natural geometry",
      lighting:   "diffused ring light, dewdrop highlights",
      photo:      "1:1 macro lens, razor-thin focus plane, focus stacking",
      medium:     "macro photography",
    },
  },
  {
    id: "food",
    label: "Food",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "appetizing, rustic-modern, rich textures, styled props",
      lighting:   "soft window side-light, gentle fill, steam catching light",
      photo:      "50mm, f/2.8, overhead and 45-degree angles",
      medium:     "food photography",
    },
  },
  {
    id: "architecture",
    label: "Architecture",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "geometric, monumental, clean lines, human scale for contrast",
      lighting:   "blue hour, interior glow against dusk sky",
      photo:      "tilt-shift, corrected verticals, wide angle",
      medium:     "architectural photography",
    },
  },
  {
    id: "long-exposure",
    label: "Long Exposure",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "ethereal, smooth motion, time made visible",
      lighting:   "twilight, light trails, silky water and streaking clouds",
      photo:      "tripod, 30-second exposure, ND filter, f/11",
      medium:     "long-exposure photography",
    },
  },
  {
    id: "polaroid",
    label: "Polaroid",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "nostalgic, faded, candid, white instant-film border",
      lighting:   "direct on-camera flash, slightly washed out",
      photo:      "instant film, soft focus, light leaks, muted color shift",
      medium:     "instant film photography",
    },
  },
  {
    id: "analog-35mm",
    label: "35mm Film",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "timeless, organic grain, true-to-life color memory",
      lighting:   "available light, honest exposure",
      photo:      "35mm film stock, visible grain, halation on highlights",
      medium:     "analog film photography",
    },
  },
  {
    id: "aerial",
    label: "Aerial",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "sweeping, patterns from above, abstract landscape geometry",
      lighting:   "low sun raking across terrain, long shadows",
      photo:      "drone top-down and oblique angles, wide dynamic range",
      medium:     "aerial drone photography",
    },
  },

  // ── Rendered / 3D ──────────────────────────────────────────────────────────
  {
    id: "octane-render",
    label: "Octane Render",
    category: "rendered",
    mode: "illustration",
    fields: {
      aesthetics: "hyperreal, pristine surfaces, physically-based materials",
      lighting:   "HDRI studio environment, soft global illumination, caustics",
      medium:     "3D render",
      art_style:  "octane render, photorealistic CGI, 8k product visualization",
    },
  },
  {
    id: "stylized-3d",
    label: "Stylized 3D",
    category: "rendered",
    mode: "illustration",
    fields: {
      aesthetics: "charming, rounded forms, big expressive eyes, animated-feature warmth",
      lighting:   "soft three-point lighting, warm bounce, subsurface scattering",
      medium:     "3D render",
      art_style:  "stylized 3D animation still, feature-film character render",
    },
  },
  {
    id: "claymation",
    label: "Claymation",
    category: "rendered",
    mode: "illustration",
    fields: {
      aesthetics: "handmade, fingerprint textures, miniature set charm",
      lighting:   "practical miniature studio lights, tiny soft shadows",
      medium:     "stop-motion claymation",
      art_style:  "plasticine stop-motion, Aardman-style claymation still",
    },
  },
  {
    id: "low-poly",
    label: "Low Poly",
    category: "rendered",
    mode: "illustration",
    fields: {
      aesthetics: "faceted, minimalist geometry, flat-shaded triangles",
      lighting:   "single directional light, hard facet shading",
      medium:     "3D render",
      art_style:  "low-poly 3D art, isometric game asset style",
    },
  },
  {
    id: "isometric",
    label: "Isometric",
    category: "rendered",
    mode: "illustration",
    fields: {
      aesthetics: "tidy diorama, miniature world, satisfying order",
      lighting:   "soft ambient occlusion, gentle top-left key",
      medium:     "3D render",
      art_style:  "isometric 3D diorama, clean game-art presentation",
    },
  },
  {
    id: "voxel",
    label: "Voxel",
    category: "rendered",
    mode: "illustration",
    fields: {
      aesthetics: "blocky, playful, pixel-art in three dimensions",
      lighting:   "soft global illumination over cubic forms",
      medium:     "3D render",
      art_style:  "voxel art, MagicaVoxel render",
    },
  },
  {
    id: "game-cinematic",
    label: "Game Cinematic",
    category: "rendered",
    mode: "illustration",
    fields: {
      aesthetics: "epic, AAA production value, atmospheric depth",
      lighting:   "dramatic volumetric god rays, particle effects, lens dirt",
      medium:     "3D render",
      art_style:  "Unreal Engine 5 cinematic, ray-traced game trailer still",
    },
  },
  {
    id: "cyberpunk-render",
    label: "Neon Cyberpunk",
    category: "rendered",
    mode: "illustration",
    fields: {
      aesthetics: "rain-slick streets, holographic ads, dense future city",
      lighting:   "neon magenta and cyan, wet reflections, fog glow",
      medium:     "3D render",
      art_style:  "cyberpunk concept render, Blade Runner-inspired CGI",
    },
  },
  {
    id: "iridescent",
    label: "Holographic",
    category: "rendered",
    mode: "illustration",
    fields: {
      aesthetics: "dreamlike chrome, oil-slick iridescence, soft gradients",
      lighting:   "studio HDRI with rainbow specular sweeps",
      medium:     "3D render",
      art_style:  "holographic iridescent 3D art, abstract chrome blobs",
    },
  },

  // ── Illustrated ────────────────────────────────────────────────────────────
  {
    id: "anime",
    label: "Anime",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "anime, vibrant, expressive, high detail",
      lighting:   "dynamic cel shading, dramatic highlights",
      medium:     "digital illustration",
      art_style:  "Japanese anime, key visual, studio-quality animation",
    },
  },
  {
    id: "concept-art",
    label: "Concept Art",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "concept art, painterly, detailed world-building",
      lighting:   "atmospheric, ambient occlusion, mood lighting",
      medium:     "digital illustration",
      art_style:  "concept art, professional illustration, ArtStation quality",
    },
  },
  {
    id: "watercolor",
    label: "Watercolor",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "soft, dreamy, organic, translucent washes",
      lighting:   "soft diffused light, watercolor glow",
      medium:     "watercolor painting",
      art_style:  "traditional watercolor, loose expressive brushwork",
    },
  },
  {
    id: "flat-design",
    label: "Flat Design",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "flat, geometric, bold, graphic design",
      lighting:   "no shadows, flat colors",
      medium:     "vector illustration",
      art_style:  "flat design, modern graphic illustration",
    },
  },
  {
    id: "oil-painting",
    label: "Oil Painting",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "rich impasto texture, classical composition, gallery presence",
      lighting:   "chiaroscuro, single warm window light",
      medium:     "oil painting on canvas",
      art_style:  "classical oil painting, visible brushstrokes, old-master technique",
    },
  },
  {
    id: "impressionist",
    label: "Impressionist",
    category: "classical",
    mode: "illustration",
    fields: {
      aesthetics: "fleeting light, broken color, outdoor immediacy",
      lighting:   "dappled sunlight, plein-air glow",
      medium:     "oil painting",
      art_style:  "impressionism, Monet-style loose dabs of pure color",
    },
  },
  {
    id: "art-nouveau",
    label: "Art Nouveau",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "ornamental, flowing organic lines, decorative borders, elegant figures",
      lighting:   "flat decorative tones with gold accents",
      medium:     "lithograph poster",
      art_style:  "Art Nouveau, Alphonse Mucha-style poster illustration",
    },
  },
  {
    id: "ukiyo-e",
    label: "Ukiyo-e",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "flattened perspective, bold outlines, wave and cloud motifs",
      lighting:   "flat woodblock tones, no cast shadows",
      medium:     "woodblock print",
      art_style:  "ukiyo-e Japanese woodblock print, Hokusai style",
    },
  },
  {
    id: "comic-book",
    label: "Comic Book",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "dynamic action, bold inks, halftone dots, panel energy",
      lighting:   "hard comic shading, dramatic spot blacks",
      medium:     "comic book illustration",
      art_style:  "American comic book art, inked linework, screen-tone shading",
    },
  },
  {
    id: "pixel-art",
    label: "Pixel Art",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "retro game charm, chunky pixels, limited palette",
      lighting:   "dithered shading, palette-constrained highlights",
      medium:     "pixel art",
      art_style:  "16-bit pixel art, SNES-era sprite style",
    },
  },
  {
    id: "childrens-book",
    label: "Children's Book",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "whimsical, gentle, friendly characters, cozy detail",
      lighting:   "soft storybook glow, warm and safe",
      medium:     "gouache illustration",
      art_style:  "children's picture-book illustration, hand-painted charm",
    },
  },
  {
    id: "ink-sketch",
    label: "Ink Sketch",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "spontaneous, confident linework, white space as air",
      lighting:   "implied by hatching and wash only",
      medium:     "pen and ink with light wash",
      art_style:  "urban sketching, crosshatched ink drawing",
    },
  },
  {
    id: "pop-art",
    label: "Pop Art",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "bold, ironic, mass-culture iconography, Ben-Day dots",
      lighting:   "flat poster lighting, hard primary-color blocks",
      medium:     "screen print",
      art_style:  "1960s pop art, Lichtenstein-style comic enlargement",
    },
  },
  {
    id: "stained-glass",
    label: "Stained Glass",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "luminous color panes, black leading, sacred geometry",
      lighting:   "backlit, sunlight streaming through colored glass",
      medium:     "stained glass window",
      art_style:  "stained-glass design, bold lead outlines, jewel tones",
    },
  },

  // ── Weird & Wonderful ─────────────────────────────────────────────────────
  {
    id: "beksinski",
    label: "Beksiński",
    category: "horror",
    mode: "illustration",
    fields: {
      aesthetics: "dystopian surrealism, decaying monumental forms, beautiful dread",
      lighting:   "sickly amber haze, light from a dying sky",
      medium:     "oil painting on hardboard",
      art_style:  "Zdzisław Beksiński-style dystopian surrealism, nightmarish fantastic realism",
    },
  },
  {
    id: "frutiger-aero",
    label: "Frutiger Aero",
    category: "aesthetic",
    mode: "illustration",
    fields: {
      aesthetics: "glossy optimism, water droplets, grass and sky, 2000s tech utopia",
      lighting:   "bright clean daylight, glassy reflections, aqua glow",
      medium:     "digital render",
      art_style:  "Frutiger Aero aesthetic, glossy skeuomorphic 2000s design, bubbles and lens flares",
    },
  },
  {
    id: "vaporwave",
    label: "Vaporwave",
    category: "aesthetic",
    mode: "illustration",
    fields: {
      aesthetics: "retro-futurist nostalgia, marble busts, palm trees, checkerboard floors",
      lighting:   "magenta and teal sunset gradient, VHS glow",
      medium:     "digital collage",
      art_style:  "vaporwave aesthetic, 80s grid horizon, Greco-Roman statues, Windows 95 motifs",
    },
  },
  {
    id: "dreamcore",
    label: "Dreamcore",
    category: "horror",
    mode: "illustration",
    fields: {
      aesthetics: "familiar yet wrong, nostalgic unease, soft surreal emptiness",
      lighting:   "overexposed flash in dim rooms, glowing doorways",
      medium:     "digital art",
      art_style:  "dreamcore weirdcore aesthetic, surreal nostalgic imagery, low-fidelity dream logic",
    },
  },
  {
    id: "liminal",
    label: "Liminal Space",
    category: "horror",
    mode: "photo",
    fields: {
      aesthetics: "empty transitional spaces, eerie stillness, nobody home",
      lighting:   "humming fluorescent tubes, no natural light",
      photo:      "flash photography, slightly tilted amateur framing",
      medium:     "found photograph",
    },
  },
  {
    id: "giger",
    label: "Biomechanical",
    category: "horror",
    mode: "illustration",
    fields: {
      aesthetics: "fusion of flesh and machine, ribbed corridors, elegant horror",
      lighting:   "cold metallic sheen, deep airbrushed shadows",
      medium:     "airbrush on board",
      art_style:  "H.R. Giger-style biomechanical art, monochrome airbrushed xenomorph design",
    },
  },
  {
    id: "dali",
    label: "Surrealist",
    category: "horror",
    mode: "illustration",
    fields: {
      aesthetics: "melting logic, impossible landscapes, precise absurdity",
      lighting:   "long desert shadows, hyper-clear horizon",
      medium:     "oil painting",
      art_style:  "Salvador Dalí-style surrealism, dreamlike precision rendering",
    },
  },
  {
    id: "cosmic-horror",
    label: "Cosmic Horror",
    category: "horror",
    mode: "illustration",
    fields: {
      aesthetics: "incomprehensible scale, tentacled geometry, humanity dwarfed",
      lighting:   "bioluminescent glow from the abyss, storm-lit silhouettes",
      medium:     "digital painting",
      art_style:  "Lovecraftian cosmic horror, eldritch dark fantasy illustration",
    },
  },
  {
    id: "glitch",
    label: "Glitch Art",
    category: "horror",
    mode: "illustration",
    fields: {
      aesthetics: "corrupted data beauty, RGB channel splits, databending artifacts",
      lighting:   "screen glow, scanline flicker",
      medium:     "digital art",
      art_style:  "glitch art, pixel sorting, chromatic aberration, datamosh",
    },
  },
  {
    id: "analog-horror",
    label: "Analog Horror",
    category: "horror",
    mode: "photo",
    fields: {
      aesthetics: "wrong broadcast, emergency-alert dread, degraded familiarity",
      lighting:   "CRT glow in a dark room, harsh camcorder light",
      photo:      "VHS tape artifacts, tracking errors, timestamp overlay",
      medium:     "found footage still",
    },
  },
  {
    id: "y2k",
    label: "Y2K Chrome",
    category: "aesthetic",
    mode: "illustration",
    fields: {
      aesthetics: "millennium futurism, liquid chrome, cyber butterflies, blobjects",
      lighting:   "studio gloss, lens-flare sparkles",
      medium:     "digital render",
      art_style:  "Y2K aesthetic, chrome liquid metal type, translucent tech plastic",
    },
  },
  {
    id: "memphis",
    label: "Memphis",
    category: "aesthetic",
    mode: "illustration",
    fields: {
      aesthetics: "playful clashing geometry, squiggles, confetti shapes, 80s postmodern",
      lighting:   "flat poster color, no shading",
      medium:     "vector illustration",
      art_style:  "Memphis Group design, 1980s postmodern pattern chaos",
    },
  },
  {
    id: "psychedelic",
    label: "Psychedelic",
    category: "aesthetic",
    mode: "illustration",
    fields: {
      aesthetics: "melting rainbows, kaleidoscopic symmetry, concert-poster swirl",
      lighting:   "vibrating complementary colors, glowing auras",
      medium:     "screen print poster",
      art_style:  "1960s psychedelic poster art, swirling op-art typography",
    },
  },
  {
    id: "solarpunk",
    label: "Solarpunk",
    category: "aesthetic",
    mode: "illustration",
    fields: {
      aesthetics: "optimistic green future, vine-wrapped architecture, community warmth",
      lighting:   "abundant sunshine through glass and leaves",
      medium:     "digital painting",
      art_style:  "solarpunk concept art, Art Nouveau meets sustainable futurism",
    },
  },
  {
    id: "dark-academia",
    label: "Dark Academia",
    category: "aesthetic",
    mode: "photo",
    fields: {
      aesthetics: "old libraries, tweed and candlelight, scholarly melancholy",
      lighting:   "low amber lamplight, dust motes in window shafts",
      photo:      "50mm, muted film stock, deep shadow detail",
      medium:     "film photography",
    },
  },
// ── Wonderful & Aesthetic (additions) ─────────────────────────────────────
  {
    id: "synthwave",
    label: "Synthwave",
    category: "aesthetic",
    mode: "illustration",
    fields: {
      aesthetics: "retro 80s night-drive, neon grids, chrome sunsets, outrun energy",
      lighting:   "glowing neon horizon, purple-orange gradient dusk",
      medium:     "digital art",
      art_style:  "synthwave outrun aesthetic, retrowave album-cover art",
    },
  },
  {
    id: "cottagecore",
    label: "Cottagecore",
    category: "aesthetic",
    mode: "photo",
    fields: {
      aesthetics: "pastoral coziness, wildflowers, linen and fresh bread, gentle nostalgia",
      lighting:   "soft morning light through cottage windows, hazy meadow sun",
      photo:      "50mm, f/2, warm film tones",
      medium:     "lifestyle film photography",
    },
  },
  {
    id: "retrofuturism",
    label: "Retrofuturism",
    category: "aesthetic",
    mode: "illustration",
    fields: {
      aesthetics: "atomic-age optimism, raygun gothic, googie curves, space-age families",
      lighting:   "bright optimistic key light, mid-century poster glow",
      medium:     "gouache poster illustration",
      art_style:  "1950s retrofuturism, atomic-age advertising art",
    },
  },
  {
    id: "art-deco",
    label: "Art Deco",
    category: "aesthetic",
    mode: "illustration",
    fields: {
      aesthetics: "geometric elegance, gold and black, sunburst motifs, Gatsby glamour",
      lighting:   "dramatic uplighting, metallic sheen",
      medium:     "screen print poster",
      art_style:  "Art Deco poster design, 1920s geometric luxury",
    },
  },
  {
    id: "ethereal-dream",
    label: "Ethereal Dream",
    category: "aesthetic",
    mode: "photo",
    fields: {
      aesthetics: "weightless, luminous, soft-focus reverie, floating fabric and light",
      lighting:   "backlit haze, prismatic flares, glowing skin tones",
      photo:      "85mm, f/1.2, pro-mist diffusion filter",
      medium:     "fine-art photography",
    },
  },
  {
    id: "fairycore",
    label: "Fairycore",
    category: "aesthetic",
    mode: "illustration",
    fields: {
      aesthetics: "enchanted forest glow, mushroom rings, glittering wings, storybook magic",
      lighting:   "dappled golden light through ancient trees, fireflies",
      medium:     "watercolor and gouache",
      art_style:  "fairycore fantasy illustration, whimsical woodland detail",
    },
  },

  // ── Weird & Horror (additions) ─────────────────────────────────────────────
  {
    id: "body-horror",
    label: "Body Horror",
    category: "horror",
    mode: "illustration",
    fields: {
      aesthetics: "anatomical wrongness, fused forms, beautiful grotesque transformation",
      lighting:   "clinical fluorescent over warm visceral tones",
      medium:     "oil painting",
      art_style:  "Cronenberg-inspired body horror, surreal anatomical art",
    },
  },
  {
    id: "junji-ito",
    label: "Junji Ito",
    category: "horror",
    mode: "illustration",
    fields: {
      aesthetics: "spiraling obsession, dense linework dread, mundane turned monstrous",
      lighting:   "stark manga blacks, hatched shadow gradients",
      medium:     "ink on paper",
      art_style:  "Junji Ito-style horror manga, meticulous crosshatched terror",
    },
  },
  {
    id: "gothic-horror",
    label: "Gothic Horror",
    category: "horror",
    mode: "illustration",
    fields: {
      aesthetics: "crumbling manors, candlelit corridors, romantic decay, Victorian dread",
      lighting:   "single candelabra, moonlight through torn curtains",
      medium:     "oil painting",
      art_style:  "gothic horror romanticism, dark academia oil technique",
    },
  },
  {
    id: "folk-horror",
    label: "Folk Horror",
    category: "horror",
    mode: "photo",
    fields: {
      aesthetics: "pagan idylls gone wrong, wicker effigies, sunlit dread in open fields",
      lighting:   "flat overcast daylight that should feel safe but does not",
      photo:      "16mm film texture, 1970s color timing",
      medium:     "film still",
    },
  },
  {
    id: "occult",
    label: "Occult",
    category: "horror",
    mode: "illustration",
    fields: {
      aesthetics: "ritual geometry, alchemical diagrams, candle smoke and sigils",
      lighting:   "ring of candlelight in absolute darkness",
      medium:     "engraving",
      art_style:  "occult woodcut engraving, esoteric grimoire illustration",
    },
  },
  {
    id: "uncanny-dolls",
    label: "Uncanny Dolls",
    category: "horror",
    mode: "photo",
    fields: {
      aesthetics: "porcelain stares, almost-human faces, dusty nursery stillness",
      lighting:   "dim attic shaft of light, deep shadow corners",
      photo:      "medium format, shallow focus on glass eyes",
      medium:     "fine-art photography",
    },
  },
// ── Classical Painting ─────────────────────────────────────────────────────
  {
    id: "renaissance",
    label: "Renaissance",
    category: "classical",
    mode: "illustration",
    fields: {
      aesthetics: "divine proportion, sfumato softness, serene idealized figures",
      lighting:   "gentle directional light, atmospheric perspective",
      medium:     "oil and tempera on panel",
      art_style:  "High Renaissance painting, Leonardo-style sfumato and balance",
    },
  },
  {
    id: "baroque",
    label: "Baroque",
    category: "classical",
    mode: "illustration",
    fields: {
      aesthetics: "theatrical intensity, dramatic gesture, darkness pierced by revelation",
      lighting:   "Caravaggio chiaroscuro, single shaft of hard light from above",
      medium:     "oil on canvas",
      art_style:  "Baroque tenebrism, Caravaggio-style dramatic realism",
    },
  },
  {
    id: "dutch-golden",
    label: "Dutch Golden Age",
    category: "classical",
    mode: "illustration",
    fields: {
      aesthetics: "quiet domestic intimacy, pearl-like detail, stillness and care",
      lighting:   "soft north window light from the left, luminous shadow",
      medium:     "oil on canvas",
      art_style:  "Dutch Golden Age interior, Vermeer-style light and calm",
    },
  },
  {
    id: "rococo",
    label: "Rococo",
    category: "classical",
    mode: "illustration",
    fields: {
      aesthetics: "powdered pastel frivolity, swirling silk, garden flirtation",
      lighting:   "airy diffused daylight, shimmering highlights on fabric",
      medium:     "oil on canvas",
      art_style:  "Rococo painting, Fragonard-style playful elegance",
    },
  },
  {
    id: "neoclassical",
    label: "Neoclassical",
    category: "classical",
    mode: "illustration",
    fields: {
      aesthetics: "stoic grandeur, marble-smooth figures, moral clarity, antique drapery",
      lighting:   "cool sculptural studio light, crisp edges",
      medium:     "oil on canvas",
      art_style:  "Neoclassicism, Jacques-Louis David-style history painting",
    },
  },
  {
    id: "romanticism",
    label: "Romanticism",
    category: "classical",
    mode: "illustration",
    fields: {
      aesthetics: "sublime nature dwarfing humanity, storm and longing, awe",
      lighting:   "turbulent skies, breaking light through clouds, glowing horizon",
      medium:     "oil on canvas",
      art_style:  "Romanticism, Caspar David Friedrich and Turner-style sublime landscape",
    },
  },
  {
    id: "pre-raphaelite",
    label: "Pre-Raphaelite",
    category: "classical",
    mode: "illustration",
    fields: {
      aesthetics: "jewel-toned medieval revival, flowing red hair, symbolic flowers",
      lighting:   "clear even daylight, every petal in focus",
      medium:     "oil on canvas",
      art_style:  "Pre-Raphaelite Brotherhood painting, Waterhouse-style romantic detail",
    },
  },
  {
    id: "post-impressionist",
    label: "Post-Impressionist",
    category: "classical",
    mode: "illustration",
    fields: {
      aesthetics: "emotional color, writhing energy, thick directional strokes",
      lighting:   "swirling night skies, halos around lights",
      medium:     "oil on canvas",
      art_style:  "Post-Impressionism, Van Gogh-style impasto swirls",
    },
  },
  {
    id: "pointillism",
    label: "Pointillism",
    category: "classical",
    mode: "illustration",
    fields: {
      aesthetics: "shimmering optical mixing, serene park scenes, dotted discipline",
      lighting:   "bright afternoon sun built from pure-color dots",
      medium:     "oil on canvas",
      art_style:  "Pointillism, Seurat-style divisionist dots",
    },
  },
  {
    id: "fauvism",
    label: "Fauvism",
    category: "classical",
    mode: "illustration",
    fields: {
      aesthetics: "wild liberated color, joy over accuracy, bold flat planes",
      lighting:   "color IS the light — vermilion shadows, green skin",
      medium:     "oil on canvas",
      art_style:  "Fauvism, Matisse-style expressive color",
    },
  },
  {
    id: "expressionism",
    label: "Expressionism",
    category: "classical",
    mode: "illustration",
    fields: {
      aesthetics: "raw psychological distortion, anxiety made visible, jagged forms",
      lighting:   "unnatural acid hues, oppressive skies",
      medium:     "oil on canvas",
      art_style:  "German Expressionism, Munch and Kirchner-style emotional distortion",
    },
  },
  {
    id: "cubism",
    label: "Cubism",
    category: "classical",
    mode: "illustration",
    fields: {
      aesthetics: "fractured simultaneous viewpoints, faceted geometry, muted earth tones",
      lighting:   "flattened analytical planes, no single light source",
      medium:     "oil on canvas",
      art_style:  "Analytical Cubism, Picasso and Braque-style fragmentation",
    },
  },
  {
    id: "klimt-golden",
    label: "Klimt Golden",
    category: "classical",
    mode: "illustration",
    fields: {
      aesthetics: "gilded ornament, mosaic patterns, embrace and ecstasy",
      lighting:   "shimmering gold-leaf glow",
      medium:     "oil and gold leaf on canvas",
      art_style:  "Gustav Klimt golden phase, Vienna Secession ornamental painting",
    },
  },
  {
    id: "symbolist",
    label: "Symbolist",
    category: "classical",
    mode: "illustration",
    fields: {
      aesthetics: "dream logic, myth and mystery, jeweled decadence",
      lighting:   "otherworldly glow from within the scene",
      medium:     "oil on canvas",
      art_style:  "Symbolism, Gustave Moreau-style mythic reverie",
    },
  },

  // ── Photography (additions) ────────────────────────────────────────────────
  {
    id: "underwater",
    label: "Underwater",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "weightless silence, shafts of blue, drifting particles",
      lighting:   "sun rays refracting down through the surface, cyan falloff",
      photo:      "underwater housing, wide angle, strobes for true color",
      medium:     "underwater photography",
    },
  },
  {
    id: "wildlife",
    label: "Wildlife",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "intimate animal portraiture, habitat context, patient observation",
      lighting:   "dawn mist light, golden backlit fur and feathers",
      photo:      "600mm telephoto, f/4, fast shutter, eye-level perspective",
      medium:     "wildlife photography",
    },
  },
  {
    id: "astro",
    label: "Astrophotography",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "Milky Way arch, cosmic scale over tiny foreground, deep night",
      lighting:   "starlight and airglow only, faint horizon glow",
      photo:      "14mm f/1.8, 20-second tracked exposure, high ISO",
      medium:     "astrophotography",
    },
  },
  {
    id: "sports-action",
    label: "Sports Action",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "peak-moment tension, frozen sweat and grit, decisive athleticism",
      lighting:   "stadium floodlights, hard rim separation",
      photo:      "400mm f/2.8, 1/2000s freeze, panning option",
      medium:     "sports photography",
    },
  },
  {
    id: "infrared",
    label: "Infrared",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "false-color dreamworld, white foliage, alien familiar landscapes",
      lighting:   "full sun rendered as snow-bright canopy",
      photo:      "infrared-converted sensor, 590nm filter",
      medium:     "infrared photography",
    },
  },
  {
    id: "tilt-shift-mini",
    label: "Tilt-Shift Mini",
    category: "photography",
    mode: "photo",
    fields: {
      aesthetics: "real world as toy diorama, miniature charm at city scale",
      lighting:   "bright saturated midday for the model-kit look",
      photo:      "tilt-shift lens, razor focal band, elevated vantage",
      medium:     "tilt-shift photography",
    },
  },

  // ── Rendered / 3D (additions) ──────────────────────────────────────────────
  {
    id: "papercraft",
    label: "Papercraft",
    category: "rendered",
    mode: "illustration",
    fields: {
      aesthetics: "layered cut paper, folded geometry, handcrafted depth",
      lighting:   "soft top light casting tiny paper shadows between layers",
      medium:     "paper diorama",
      art_style:  "papercraft layered paper-cut art, origami-inspired 3D scene",
    },
  },
  {
    id: "needle-felt",
    label: "Needle Felt",
    category: "rendered",
    mode: "illustration",
    fields: {
      aesthetics: "fuzzy wool warmth, handmade imperfection, huggable characters",
      lighting:   "soft window light catching individual fibers",
      medium:     "needle-felted wool",
      art_style:  "needle felt stop-motion style, fuzzy wool miniature",
    },
  },
  {
    id: "toy-bricks",
    label: "Toy Bricks",
    category: "rendered",
    mode: "illustration",
    fields: {
      aesthetics: "modular plastic brick world, studs and seams, playset charm",
      lighting:   "clean toy-photography lighting, glossy plastic highlights",
      medium:     "3D render",
      art_style:  "plastic building-brick render, minifigure-scale diorama",
    },
  },
  {
    id: "porcelain",
    label: "Porcelain",
    category: "rendered",
    mode: "illustration",
    fields: {
      aesthetics: "delicate glazed figurines, blue-on-white painted detail, fragile elegance",
      lighting:   "museum vitrine lighting, soft specular glaze",
      medium:     "porcelain sculpture",
      art_style:  "glazed porcelain figurine render, fine ceramic detail",
    },
  },
  {
    id: "inflatable",
    label: "Inflatable",
    category: "rendered",
    mode: "illustration",
    fields: {
      aesthetics: "puffy balloon forms, taut shiny vinyl, playful squish",
      lighting:   "bright studio softbox, big specular balloon highlights",
      medium:     "3D render",
      art_style:  "inflatable balloon 3D art, glossy vinyl blow-up objects",
    },
  },
  {
    id: "gummy",
    label: "Gummy Candy",
    category: "rendered",
    mode: "illustration",
    fields: {
      aesthetics: "translucent jelly glow, sugar-dusted edges, edible everything",
      lighting:   "backlit subsurface scattering through candy flesh",
      medium:     "3D render",
      art_style:  "gummy candy render, translucent jelly material study",
    },
  },

  // ── Illustrated (additions) ────────────────────────────────────────────────
  {
    id: "ligne-claire",
    label: "Ligne Claire",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "uniform clean outlines, flat color, clear readable adventure",
      lighting:   "no hatching, shadow as flat shape only",
      medium:     "ink and flat color",
      art_style:  "ligne claire Franco-Belgian comic style, Tintin-school clarity",
    },
  },
  {
    id: "graffiti",
    label: "Graffiti",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "wildstyle letters, drips and fades, urban wall energy",
      lighting:   "flat daylight on brick, aerosol sheen",
      medium:     "spray paint on wall",
      art_style:  "graffiti street art, wildstyle burner with character",
    },
  },
  {
    id: "botanical-plate",
    label: "Botanical Plate",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "scientific elegance, labeled specimens, antique paper",
      lighting:   "flat even illustration light",
      medium:     "copperplate engraving with watercolor",
      art_style:  "vintage botanical illustration, 19th-century natural history plate",
    },
  },
  {
    id: "tarot",
    label: "Tarot Card",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "mystic symbolism, ornate borders, archetypal figures",
      lighting:   "flat medieval shading with celestial accents",
      medium:     "illustrated card",
      art_style:  "Rider-Waite-inspired tarot card art, esoteric line and wash",
    },
  },
  {
    id: "tattoo-flash",
    label: "Tattoo Flash",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "bold iconic motifs, banners and daggers, sailor swagger",
      lighting:   "none — bold line and solid fill",
      medium:     "flash sheet",
      art_style:  "American traditional tattoo flash, thick lines, limited palette",
    },
  },
  {
    id: "paper-collage",
    label: "Paper Collage",
    category: "illustrated",
    mode: "illustration",
    fields: {
      aesthetics: "torn and cut shapes, layered texture, playful composition",
      lighting:   "subtle real shadows between paper layers",
      medium:     "cut-paper collage",
      art_style:  "Matisse-style cut-out collage, hand-torn paper shapes",
    },
  },

  // ── Wonderful & Aesthetic (additions) ──────────────────────────────────────
  {
    id: "steampunk",
    label: "Steampunk",
    category: "aesthetic",
    mode: "illustration",
    fields: {
      aesthetics: "brass and leather, exposed gears, Victorian invention romance",
      lighting:   "warm gaslight and boiler glow, steam haze",
      medium:     "digital painting",
      art_style:  "steampunk concept art, Victorian retro-tech detail",
    },
  },
  {
    id: "wabi-sabi",
    label: "Wabi-Sabi",
    category: "aesthetic",
    mode: "photo",
    fields: {
      aesthetics: "imperfect beauty, weathered texture, emptiness as luxury",
      lighting:   "single soft window, long quiet shadows",
      photo:      "50mm, natural film tones, deliberate negative space",
      medium:     "fine-art photography",
    },
  },
  {
    id: "kawaii-pastel",
    label: "Kawaii Pastel",
    category: "aesthetic",
    mode: "illustration",
    fields: {
      aesthetics: "round-cheeked cuteness, candy pastels, sparkles and blush",
      lighting:   "soft dreamy glow, no hard shadows",
      medium:     "digital illustration",
      art_style:  "kawaii pastel art, chibi proportions, sticker-sheet charm",
    },
  },
  {
    id: "disco-glam",
    label: "Disco Glam",
    category: "aesthetic",
    mode: "photo",
    fields: {
      aesthetics: "mirror-ball sparkle, sequins and satin, 70s nightlife euphoria",
      lighting:   "spinning mirror-ball speckles, colored gel spots",
      photo:      "85mm, starburst filter, kodachrome warmth",
      medium:     "fashion photography",
    },
  },

  // ── Weird & Horror (additions) ─────────────────────────────────────────────
  {
    id: "spirit-photo",
    label: "Spirit Photography",
    category: "horror",
    mode: "photo",
    fields: {
      aesthetics: "Victorian seance, translucent figures, sincere fakery turned real",
      lighting:   "harsh early flash powder, vignetted darkness",
      photo:      "wet-plate collodion, double exposure ghosting, scratched plate",
      medium:     "antique daguerreotype",
    },
  },
  {
    id: "trailcam",
    label: "Trailcam Cryptid",
    category: "horror",
    mode: "photo",
    fields: {
      aesthetics: "something in the treeline, motion-triggered dread, almost-identifiable shape",
      lighting:   "infrared night-vision glare, white reflective eyes",
      photo:      "trail camera, timestamp overlay, low resolution noise",
      medium:     "trail camera footage",
    },
  },
  {
    id: "memento-mori",
    label: "Memento Mori",
    category: "horror",
    mode: "illustration",
    fields: {
      aesthetics: "vanitas still life, skulls and wilting flowers, time running out beautifully",
      lighting:   "single candle against velvet black",
      medium:     "oil on canvas",
      art_style:  "Dutch vanitas still life, memento mori symbolism",
    },
  },
  {
    id: "sleep-paralysis",
    label: "Sleep Paralysis",
    category: "horror",
    mode: "illustration",
    fields: {
      aesthetics: "weight on the chest, watcher in the doorway, bedroom geometry gone wrong",
      lighting:   "moonlight through blinds, a shadow darker than the dark",
      medium:     "digital painting",
      art_style:  "sleep paralysis horror art, Fuseli Nightmare descendant",
    },
  },
]
